### PR TITLE
Update machine_learning.md 

### PR DESCRIPTION
**Pull request by keep9oing**
Previous manual doesn't activate the conda environment after create it.
The (base) and (tensorflow) prefix should be written.

### CODE REVIEW

**Comment by ROBOTIS-David** [comment]
@keep9oing 

Hi, I am sorry that I have missed this request, and thank you for your helping as well.
I reported this request to the one who is in charge of TurtleBot3. 

Thank you. 

@ROBOTIS-Will  
I wonder if you could simply review the file requested from our sophisticated user? 

and let me know if I need to update it 

Thank you.

**Comment by ROBOTIS-Will** [comment]
@keep9oing 
Thanks for the PR.
Creating and running ROS on conda environment can cause python interpreter issues such as rospkg import error, but we'll see if there's a better way to adopt your PR into our eManual.
https://answers.ros.org/question/282982/how-importerror-no-module-named-rospkg-happens/

**Comment by bluedaze** [comment]
Is there plans on updating this?

**Comment by robotpilot** [comment]
We're closing this PR because it's out of date, but we'll work on getting the content you're talking about up and running. 
Thank you.

**Pull request closed without merging**
