### PR TITLE
Dynamixel Protocol 2.1 - ID Conflict Resolution support

### PR DESCRIPTION
**Pull request by LucidOne**
We would like to propose the following [changes](https://github.com/dabit-industries/emanual/blob/protocol-conflict/docs/en/dxl/protocol2.md) to the Dynamixel Protocol as the first step towards automatic ID conflict resolution. These changes should help detect ID conflicts and provide a means for controllers to update Device IDs without disassembling robots!

In addition to updating the protocol, the Dynamixel and Controller firmwares will also need to be updated. While the proposed changes can not provide a means for Controllers running Protocol 2.1 to resolve ID conflicts between servos running Protocol 2.0, they should otherwise be compatible.

### ID Conflict Resolution Process Example
Given that the controller knows the number of Dynamixels attached the process can run iteratively until all of the Devices are detected.

1) Controller sends a `Ping` Instruction to the broadcast ID
2) Controller detect corrupted messages or the incorrect number of devices detected
3) Controller sends a [`Random Ping`](https://github.com/dabit-industries/emanual/blob/protocol-conflict/docs/en/dxl/protocol2.md#random-ping) Instruction to each ID that may be in conflict
4) For each ID that has more than one Dynamixel assigned, the controller sends a [`Random Sleep`](https://github.com/dabit-industries/emanual/blob/protocol-conflict/docs/en/dxl/protocol2.md#random-sleep) Instruction
5) As each Device responds, the controller reassigns it to an available ID
6) The process repeats until the correct number of Devices are detected

Depending on the memory/cpu resources available on the Dynamixels, this process may be optimized.

### CODE REVIEW

**Comment by ROBOTIS-Will** [comment]
Hi @LucidOne ,

Thank you so much for your proposal to resolve ID conflicting issue.
I'll deliver your idea to the Dynamixel department so that they can review it.
Thanks!

**Comment by LucidOne** [comment]
Hello @ROBOTIS-Will,

Thanks for the update. We are open to implementing Protocol 2.1 ID Conflict Resolution on the OpenCR Controller and possibly others. If anyone in the Dynamixel department has technical questions regarding implementation, @RobotisBrandon has [our](https://dabit.industries/) contact information.

**Comment by ROBOTIS-Will** [comment]
@LucidOne ,
As your idea requires significant changes in all Dynamixel firmware, we need to consider this modification as a long term project if it is accepted.
Thank you so much for your contribution and in order to prevent accidental merge into the master branch, I'll close this thread for now.
However, please feel free to reopen this thread or create another one whenever you have a great idea for improvement.
Thank you! 👍

**Comment by ROBOTIS-Will** [comment]
@LucidOne ,
Below is the message from the development department.
------------
We appreciate for your suggestion.
Using a Random Ping to resolve ID conflict looks like a smart approach.
We are also in great anguish at avoiding ID conflict in daisy-chain connection, and consistently looking for the solution.
We've been also considered using a Random function with seed value, but there are still chances of having identical ID so we thought it wouldn't be the optimized solution that we are looking for.
There could be a solution that we didn't find out, and your opinion really helps us to search for the answer that we might haven't thought about.
Thank you very much for your idea!

**Comment by LucidOne** [comment]
Thanks for the update!

We understand that even if seeding from voltage + position + temperature provides good randomness there is still a chance of having the same ID selected. This is why we would plan to have the controller apply the process iteratively until all Dynamixels are detected and the number of Dynamixels attached needs to be specified.

Part of the is due to the limited number of timeslots for Dynamixels to respond, this could be improved by providing more timeslots (pick a random number 0-2048) to reduce collisions. The tradeoff here is that the window needs to be long enough for a Dynamixel to wake up and the controller to reconfigure it before another one wakes up. Testing would be required to determine the minimum sleep timeslot.

Another approach may require a bit more work from an implementation stand point and depend on how much cpu and memory is available on the Dynamixel. If each device selects a random time T_n (0000-FFFF * 1ms) and waits for this time period before announcing that it is ready to be configured. If instead of having the Dynamixels sleep, they would enter "listen" mode and if another device at time T_a announces that is is ready to be configured and T_n-T_a < 100ms the Dynamixel would select a new timeslot. This would allow for very small time slots. This approach is similar to how [ethernet collision detection](https://en.wikipedia.org/wiki/Carrier_sense_multiple_access_with_collision_detection) works.

**Comment by LucidOne** [comment]
@ROBOTIS-Will Did you have a chance to forward my additional comments?
Thanks!

**Comment by ROBOTIS-Will** [comment]
@LucidOne Sorry, I never get used to this github notification. Yes, your message was delivered to the development department! Thank you :D

**Pull request closed without merging**
