### PR TITLE
added verified instructions of setting up static ip on tb3 rp3

### PR DESCRIPTION
**Pull request by aaronchongth**
Just started tried setting up the Raspberry Pi 3 of a Turtlebot3 Burger, an encountered some issues while following the documentation. Here are some of the changes I believe will be useful,

* some information regarding flashing the SD card of the Pi

* the instructions for `touch` and configuring `/etc/netplan/01-netcfg.yaml` did not work for me, (I believe there might have been some changes since the last image of Ubuntu 18 Server for Pi3?)

* for general robotic use cases, having static IP addresses on the network will be more desirable, just in case the dynamic IP allocation changes for whatever reason

* also added some references for the network setup

### CODE REVIEW

**Comment by routiful** [comment]
@aaronchongth 
Thank you for your comments. But I recommended that you would get a new ticket in [TurtleBot3 Issue](https://github.com/ROBOTIS-GIT/turtlebot3/issues) page to ask this issue to TurtleBot3 developer.

**Comment by ROBOTIS-David** [comment]
> Just started tried setting up the Raspberry Pi 3 of a Turtlebot3 Burger, an encountered some issues while following the documentation. Here are some of the changes I believe will be useful,
> 
> * some information regarding flashing the SD card of the Pi
> * the instructions for `touch` and configuring `/etc/netplan/01-netcfg.yaml` did not work for me, (I believe there might have been some changes since the last image of Ubuntu 18 Server for Pi3?)
> * for general robotic use cases, having static IP addresses on the network will be more desirable, just in case the dynamic IP allocation changes for whatever reason
> * also added some references for the network setup


Thank

**Comment by ROBOTIS-David** [comment]
@aaronchongth  
Hi ! On behalf of everyone in ROBOTIS, I very appreciate your attention to e-Manual. As e-Manual is managed to be improved by all users, your suggestion will be very carefully investigated ! 
Until then I would like to shelve here ! Once again, thanks you very much for your attention. 

Truly, 

David Park.

**Comment by aaronchongth** [comment]
@routiful @ROBOTIS-David thanks for the quick replies, no problem! I assumed some of these could have been instructions for past Pi images so did not think they were issues. I also could not find a contribution guide so I decided to do a PR instead. Cheers!

**Pull request closed without merging**
