### PR TITLE
ros2: ignore packages instead of rm from git clone

### PR DESCRIPTION
**Pull request by russkel**
Ignore packages instead of having to delete them. Also, perhaps maybe explain why we aren't building these?

### CODE REVIEW

**Comment by ROBOTIS-Will** [comment]
@russkel 
Both PC and TurtleBot3 SBC use identical package, but usually SBCs have relatively smaller storage compare to the PC, so it is recommended to delete unused packages instead of ignoring them.
Later we will review if we can separate these packages from the TurtleBot3 package.
Thank you.

**Comment by russkel** [comment]
It's only a couple of megabytes on a 16GB SD card?

rm'ing from a git repository is poor practice as it somewhat breaks the git repository and you have to reset in order to pull in new commits.

**Comment by russkel** [comment]
And if you're seriously concerned about space (which you shouldn't be, in my opinion) all the git clones should be shallow clones.

**Comment by ROBOTIS-Will** [comment]
Thank you for the insights on these unused packages. We'll come up with some plans for lighter packages with faster building time. I believe this will be applied along with the Foxy since Dashing and Eloquent will reach to their EOL soon.

**Pull request closed without merging**
